// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzLjk9q5pNez2Bv65_0b5zz-yxiH2azFA',
    appId: '1:541870879845:web:fee570ccf2b9091f70828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    authDomain: 'sphare-3fd0c.firebaseapp.com',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
    measurementId: 'G-JF3TEVT72V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_OXSATucPz8-VIn6pzssb_ksYLt3aXJA',
    appId: '1:541870879845:android:cb76808e4b5d6f4c70828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ZL5ed4WARLwI7ENMKrdHroMCJEWcXPk',
    appId: '1:541870879845:ios:3cb691acd1193b1770828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
    iosBundleId: 'com.moc.sphareshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ZL5ed4WARLwI7ENMKrdHroMCJEWcXPk',
    appId: '1:541870879845:ios:58df0cbc3382414770828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzLjk9q5pNez2Bv65_0b5zz-yxiH2azFA',
    appId: '1:541870879845:web:42136ff20a30ff0370828c',
    messagingSenderId: '541870879845',
    projectId: 'sphare-3fd0c',
    authDomain: 'sphare-3fd0c.firebaseapp.com',
    storageBucket: 'sphare-3fd0c.firebasestorage.app',
    measurementId: 'G-8X43DE73X5',
  );

}